In [0]:
import numpy as np
import pandas as pd

## Numpy

In [0]:
a = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])  
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
print(a.ndim) #número de dimensiones
print(a.shape)#tupla con las dimensiones del arreglo
print(a.size) #número de elementos

2
(3, 4)
12


Funciones especiales

In [0]:
print(np.zeros((3,3))) #array de zeros
print(np.ones([5,1])) #array de unos
print(np.eye(4)) #matriz identidad
print(np.empty((2,3), dtype=int))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[10 10 10]
 [10 10 10]]


Operaciones con arrays

In [0]:
a*a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [0]:
a+a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [0]:
2*a

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

Funciones

In [0]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [0]:
b = np.sqrt(a)
b

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [0]:
np.exp(b) #eleva e a la b

array([1.        , 2.71828183, 4.11325038, 5.65223367, 7.3890561 ])

In [0]:
np.add(a,a) #suma 2 arrays

array([0, 2, 4, 6, 8])

In [0]:
np.multiply(a,a) #multiplicacion elemento a elemento (no de matrices)

array([ 0,  1,  4,  9, 16])

Métodos matemáticos

In [0]:
h = np.arange(9).reshape(3,3)
h

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
h.mean()

4.0

In [0]:
h.sum(axis=1) #suma de filas

array([ 3, 12, 21])

In [0]:
h.max(axis=0) #máximo de columnas

array([6, 7, 8])

Slicing and indexing

In [0]:
a = np.arange(64).reshape(4,4,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [0]:
a[1,2,1]

25

In [0]:
a[1,:,2]

array([18, 22, 26, 30])

In [0]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
a[1,1] #fila 1 elemento 1
a[2,2] #fila 2 elemento 2
a[[1,2],[1,2]] #y así lo devolvemos todo completo

array([ 6, 12])

Filtros

In [0]:
x= np.array([1, 2, 3, 4, 5])
y = np.array([1.5, 2.5, 3.5, 4.5, 5.5])

In [0]:
np.where(x>2.5, True, False)

array([False, False,  True,  True,  True])

## Pandas

Series

In [0]:
serie = pd.Series([10, 11, 12, 13])
serie

0    10
1    11
2    12
3    13
dtype: int64

In [0]:
serie.values

array([10, 11, 12, 13])

In [0]:
serie.index

RangeIndex(start=0, stop=4, step=1)

Data Frames

In [0]:
data = {'provincia': ['Valencia', 'Madrid', 'Soria', 'Málaga', 'Teruel'],
        'Año': [2000, 2001, 2002, 2001, 2002],
        'Población': [1.5, 1.7, 3.6, 2.4, 2.9]}
df = pd.DataFrame(data, index = ['a','b','c','d','e'])
df

provincia   Año  Población
a  Valencia  2000        1.5
b    Madrid  2001        1.7
c     Soria  2002        3.6
d    Málaga  2001        2.4
e    Teruel  2002        2.9

In [0]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [0]:
df.columns

Index(['provincia', 'Año', 'Población'], dtype='object')

In [0]:
df['Año'].dtype

dtype('int64')

In [0]:
type(df['Año'])

pandas.core.series.Series

In [0]:
df['Año']

a    2000
b    2001
c    2002
d    2001
e    2002
Name: Año, dtype: int64

In [0]:
df[['Año']]

Año
a  2000
b  2001
c  2002
d  2001
e  2002

In [0]:
df[['Año', 'provincia']]

Año provincia
a  2000  Valencia
b  2001    Madrid
c  2002     Soria
d  2001    Málaga
e  2002    Teruel

In [0]:
df.loc['c']

provincia    Soria
Año           2002
Población      3.6
Name: c, dtype: object

In [0]:
df.iloc[2]

provincia    Soria
Año           2002
Población      3.6
Name: c, dtype: object

Métodos

In [0]:
data = pd.read_csv('pokemon.csv', sep=',')

In [0]:
data.head()

#           Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  \
0  1      Bulbasaur  Grass  Poison  45      49       49       65       65   
1  2        Ivysaur  Grass  Poison  60      62       63       80       80   
2  3       Venusaur  Grass  Poison  80      82       83      100      100   
3  4  Mega Venusaur  Grass  Poison  80     100      123      122      120   
4  5     Charmander   Fire     NaN  39      52       43       60       50   

   Speed  Generation  Legendary  
0     45           1      False  
1     60           1      False  
2     80           1      False  
3     80           1      False  
4     65           1      False

In [0]:
data.tail()

#            Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  \
795  796         Diancie     Rock  Fairy  50     100      150      100   
796  797    Mega Diancie     Rock  Fairy  50     160      110      160   
797  798  Hoopa Confined  Psychic  Ghost  80     110       60      150   
798  799   Hoopa Unbound  Psychic   Dark  80     160       60      170   
799  800       Volcanion     Fire  Water  80     110      120      130   

     Sp. Def  Speed  Generation  Legendary  
795      150     50           6       True  
796      110    110           6       True  
797      130     70           6       True  
798      130     80           6       True  
799       90     70           6       True

In [0]:
data.shape

(800, 12)

In [0]:
data.values

array([[1, 'Bulbasaur', 'Grass', ..., 45, 1, False],
       [2, 'Ivysaur', 'Grass', ..., 60, 1, False],
       [3, 'Venusaur', 'Grass', ..., 80, 1, False],
       ...,
       [798, 'Hoopa Confined', 'Psychic', ..., 70, 6, True],
       [799, 'Hoopa Unbound', 'Psychic', ..., 80, 6, True],
       [800, 'Volcanion', 'Fire', ..., 70, 6, True]], dtype=object)

In [0]:
data.describe()

#          HP      Attack     Defense     Sp. Atk     Sp. Def  \
count  800.0000  800.000000  800.000000  800.000000  800.000000  800.000000   
mean   400.5000   69.258750   79.001250   73.842500   72.820000   71.902500   
std    231.0844   25.534669   32.457366   31.183501   32.722294   27.828916   
min      1.0000    1.000000    5.000000    5.000000   10.000000   20.000000   
25%    200.7500   50.000000   55.000000   50.000000   49.750000   50.000000   
50%    400.5000   65.000000   75.000000   70.000000   65.000000   70.000000   
75%    600.2500   80.000000  100.000000   90.000000   95.000000   90.000000   
max    800.0000  255.000000  190.000000  230.000000  194.000000  230.000000   

            Speed  Generation  
count  800.000000   800.00000  
mean    68.277500     3.32375  
std     29.060474     1.66129  
min      5.000000     1.00000  
25%     45.000000     2.00000  
50%     65.000000     3.00000  
75%     90.000000     5.00000  
max    180.000000     6.00000

In [0]:
data.info

<bound method DataFrame.info of        #                    Name    Type 1  Type 2   HP  Attack  Defense  \
0      1               Bulbasaur     Grass  Poison   45      49       49   
1      2                 Ivysaur     Grass  Poison   60      62       63   
2      3                Venusaur     Grass  Poison   80      82       83   
3      4           Mega Venusaur     Grass  Poison   80     100      123   
4      5              Charmander      Fire     NaN   39      52       43   
5      6              Charmeleon      Fire     NaN   58      64       58   
6      7               Charizard      Fire  Flying   78      84       78   
7      8        Mega Charizard X      Fire  Dragon   78     130      111   
8      9        Mega Charizard Y      Fire  Flying   78     104       78   
9     10                Squirtle     Water     NaN   44      48       65   
10    11               Wartortle     Water     NaN   59      63       80   
11    12               Blastoise     Water     NaN   79 

In [0]:
data.nunique()

#             800
Name          799
Type 1         18
Type 2         18
HP             94
Attack        111
Defense       103
Sp. Atk       105
Sp. Def        92
Speed         108
Generation      6
Legendary       2
dtype: int64